import Head from 'next/head'

export default function Home() {
  return (
    <div className='container mx-auto'>
      <Head>
        <title>Zone LMS</title>
        <meta name="description" content="Generated by Zone LMS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='transparent-48 bg-primary-lighter text-grey-900'>Hello World</h1>
    </div>
  )
}
